added addtocalendar button to single event view
mix-movement/GetTogether pull request #5
Opened 2019-05-03 12:45 UTC by thiagoferreiraw

2019-05-03 13:10 UTC, kahenvay commented
Added add to calendar button to single event / event details view (show_event.html).

<img width="1135" alt="Screenshot 2019-05-03 at 15 08 34" src="https://user-images.githubusercontent.com/8895202/57139405-7c188280-6db5-11e9-9c7a-3fe0302ce8f9.png">

2019-05-06 23:41 UTC, thiagoferreiraw commented
It didn't work for me buddy. Here is the error report the `AddEvent` created:

https://www.addevent.com/create/?service=appleical&dstart=7%20de%20Mai%20de%202019%20%C3%A0s%2000%3A00&dend=7%20de%20Mai%20de%202019%20%C3%A0s%2000%3A00&dsum=aaaaaaaaaa&ddesc=aaaaaaaaaaaaaaaaaaaaa&dloca=Brick%20Caf%C3%A9%20Lisboa&reference=http://localhost:8000

It's probably related to the date i10n. Perhaps we have to format before sending them?

2019-05-06 23:42 UTC, thiagoferreiraw commented
Also, please check if it works with different timezones ;)  Thank you!

2019-05-07 16:51 UTC, kahenvay commented
Ah, nice catch. Sorry I missed that. I'll solve it tomorrow

2019-05-09 14:12 UTC, pawalls-zz requested changes
Looks great overall, @kahenvay! Minor whitespace/style knits.

2019-05-09 14:12 UTC, pawalls-zz commented on get_together/templates/get_together/events/show_event.html
> +    // console.log('formatDate', formatDate('{{event.local_start_time}}'));
Please clean-up comment before submit.

2019-05-09 14:12 UTC, pawalls-zz commented on get_together/templates/get_together/events/show_event.html
> +            <h2> {{ event.name }}</h2>
Stray whitespace or is this intentional?

2019-05-09 14:17 UTC, pawalls commented on get_together/templates/get_together/events/show_event.html
> +<script type="text/javascript" src="https://addevent.com/libs/atc/1.6.1/atc.min.js" async defer></script>
Non-blocking FYI:

Ultimately, we will want to host all Javascript ourselves. Third-party JS makes our frontend less likely to work with things like uBlock/uMatrix and also opens our users to external tracking. In the long run, we may need to push emergency fixes for these as well (for security, etc).

We need to establish a pattern here and a mechanism for vendoring. I've thrown a story for this on the icebox.

2019-05-10 06:52 UTC, kahenvay commented on get_together/templates/get_together/events/show_event.html
> +            <h2> {{ event.name }}</h2>
Stray, removed

2019-05-10 06:53 UTC, kahenvay commented on get_together/templates/get_together/events/show_event.html
> +    // console.log('formatDate', formatDate('{{event.local_start_time}}'));
Yes sorry! I made myself a little checklist to look at before pushing now.

2019-05-11 00:33 UTC, thiagoferreiraw commented
PR reviewed Tested! 
Thank you @kahenvay !

2019-05-11 00:33 UTC, merged