made logo configurable (theme engine)
mix-movement/GetTogether pull request #9
Opened 2019-05-12 18:11 UTC by georgesco94

Made path to logo part of theming engine

<img width="1222" alt="Screen Shot 2019-05-12 at 2 09 46 PM" src="https://user-images.githubusercontent.com/22419833/57586154-a4903300-74bf-11e9-8c68-4a9884747e97.png">

2019-05-14 00:26 UTC, thiagoferreiraw requested changes
Please remove the file .DS_Store.

You can also add it to the .gitignore ;)

2019-05-14 00:28 UTC, thiagoferreiraw commented
Regarding being able to change the logo, everything is working fine! 

@pawalls, we are going to need further adjustments in the graphic design such as colors, fonts, sizes... This isn't in the scope of this issue, right? If so, we are good to merge then! But let's create an issue for other branding changes.

2019-05-14 18:44 UTC, pawalls-zz approved these changes
Nice work, George.

2019-05-15 01:11 UTC, thiagoferreiraw approved these changes

2019-05-15 01:11 UTC, merged